### ISSUE TITLE
embeded link to voltairine.fr

### ISSUE THREAD

**Issue by sachaz** [Psycojoker/soya#1]
changer le lien de l'embeded de woldomination.be pour voltairine.fr

**Comment by Psycojoker** [comment]
Fixed. (enfin, j'ai mis "envoi.voltairine.fr", j'espère que c'est bien ça que tu voulais).

**Comment by sachaz** [comment]
le mieux c'est d'avoir un fichier de conf non ?

**Comment by sachaz** [comment]
sinon oui c'était ça merci !

**Comment by Psycojoker** [comment]
en fait c'est déjà dans un fichier de conf: dans <code>/home/voltairine/voltairine/settings_local.py</code> si je dis pas de bétises.
